version: '3'

volumes:
  pg_data_production_kit:
  static_volume_kit:
  media_volume_kit:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production_kit:/var/lib/postgresql/data/

  backend:
    image: vladimirpichuev/kittygram_backend
    env_file: .env
    depends_on: 
      - db
    volumes:
      - static_volume_kit:/backend_static/
      - media_volume_kit:/cats/media

  frontend:
    env_file: .env
    image: vladimirpichuev/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume_kit:/frontend_static/

  gateway:
    image: vladimirpichuev/kittygram_nginx
    env_file: .env
    depends_on:
      - backend
      - frontend
    ports:
      - 9000:80
    volumes:
      - static_volume_kit:/staticfiles/
      - media_volume_kit:/cats/media
