version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: vladimirpichuev/kittygram_backend
    env_file: .env
    depends_on: 
      - db
    volumes:
      - static:/backend_static/static
      - media:/app/media/

  frontend:
    env_file: .env
    image: vladimirpichuev/kittygram_frontend
    depends_on:
      - db
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    image: vladimirpichuev/kittygram_gateway
    env_file: .env
    depends_on:
      - backend
      - frontend
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles
      - media:/media
